# SPDX-FileCopyrightText: 2026 LennyK
# SPDX-License-Identifier: GPL-3.0-or-later
"""add app_settings singleton table

Revision ID: 05ae499e7e18
Revises: fd7f67c58b1e
Create Date: 2026-04-27 13:40:49.792383

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '05ae499e7e18'
down_revision: str | Sequence[str] | None = 'fd7f67c58b1e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spoolman_url', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('spoolman_auto_sync', sa.Boolean(), nullable=False),
    sa.Column('spoolman_sync_interval_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
