# SPDX-FileCopyrightText: 2026 LennyK
# SPDX-License-Identifier: GPL-3.0-or-later
"""initial schema

Revision ID: 8da961725bbd
Revises: 
Create Date: 2026-04-27 10:02:47.539823

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8da961725bbd'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filament',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('material', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('color_hex', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('hotend_temp_min', sa.Integer(), nullable=True),
    sa.Column('hotend_temp_max', sa.Integer(), nullable=True),
    sa.Column('bed_temp', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spoolman_filament_id', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filament', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filament_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_filament_spoolman_filament_id'), ['spoolman_filament_id'], unique=True)

    op.create_table('printer',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('build_volume', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_printer_name'), ['name'], unique=False)

    op.create_table('slicer',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('profile_format', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slicer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slicer_name'), ['name'], unique=False)

    op.create_table('nozzle',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('diameter_mm', sa.Float(), nullable=False),
    sa.Column('material', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nozzle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nozzle_printer_id'), ['printer_id'], unique=False)

    op.create_table('print_profile',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('layer_height_mm', sa.Float(), nullable=False),
    sa.Column('quality_label', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('nozzle_id', sa.Integer(), nullable=False),
    sa.Column('filament_id', sa.Integer(), nullable=False),
    sa.Column('slicer_id', sa.Integer(), nullable=False),
    sa.Column('active_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filament_id'], ['filament.id'], ),
    sa.ForeignKeyConstraint(['nozzle_id'], ['nozzle.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.ForeignKeyConstraint(['slicer_id'], ['slicer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_profile_active_version_id'), ['active_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_profile_filament_id'), ['filament_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_profile_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_profile_nozzle_id'), ['nozzle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_profile_printer_id'), ['printer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_profile_slicer_id'), ['slicer_id'], unique=False)

    op.create_table('profile_version',
    sa.Column('change_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('rating_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=True),
    sa.Column('raw_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('raw_format', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('raw_blob_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['print_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_version_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_version_version_no'), ['version_no'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_version_version_no'))
        batch_op.drop_index(batch_op.f('ix_profile_version_profile_id'))

    op.drop_table('profile_version')
    with op.batch_alter_table('print_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_profile_slicer_id'))
        batch_op.drop_index(batch_op.f('ix_print_profile_printer_id'))
        batch_op.drop_index(batch_op.f('ix_print_profile_nozzle_id'))
        batch_op.drop_index(batch_op.f('ix_print_profile_name'))
        batch_op.drop_index(batch_op.f('ix_print_profile_filament_id'))
        batch_op.drop_index(batch_op.f('ix_print_profile_active_version_id'))

    op.drop_table('print_profile')
    with op.batch_alter_table('nozzle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nozzle_printer_id'))

    op.drop_table('nozzle')
    with op.batch_alter_table('slicer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slicer_name'))

    op.drop_table('slicer')
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_printer_name'))

    op.drop_table('printer')
    with op.batch_alter_table('filament', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filament_spoolman_filament_id'))
        batch_op.drop_index(batch_op.f('ix_filament_name'))

    op.drop_table('filament')
    # ### end Alembic commands ###
