# SPDX-FileCopyrightText: 2026 LennyK
# SPDX-License-Identifier: GPL-3.0-or-later
"""add spoolman_public_url to app_settings

Revision ID: 9a217fd8d3e2
Revises: 05ae499e7e18
Create Date: 2026-04-27 13:52:30.194241

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a217fd8d3e2'
down_revision: str | Sequence[str] | None = '05ae499e7e18'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoolman_public_url', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('spoolman_public_url')

    # ### end Alembic commands ###
