# SPDX-FileCopyrightText: 2026 LennyK
# SPDX-License-Identifier: GPL-3.0-or-later
"""add build_plate table and FK on print_profile

Revision ID: fd7f67c58b1e
Revises: 8da961725bbd
Create Date: 2026-04-27 10:58:36.009393

"""
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fd7f67c58b1e'
down_revision: str | Sequence[str] | None = '8da961725bbd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_plate',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('surface_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('finish', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('bed_temp_min', sa.Integer(), nullable=True),
    sa.Column('bed_temp_max', sa.Integer(), nullable=True),
    sa.Column('compatible_materials', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('build_plate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_plate_name'), ['name'], unique=False)

    with op.batch_alter_table('print_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('build_plate_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_print_profile_build_plate_id'), ['build_plate_id'], unique=False)
        batch_op.create_foreign_key('fk_print_profile_build_plate', 'build_plate', ['build_plate_id'], ['id'])

    # ### end Alembic commands ###

    # ----- Seed common build plates so users have a starting catalogue. -----
    # Sources (researched 2026-04-27):
    #  - Bambu Lab Wiki: Cool Plate SuperTack, Smooth/Textured PEI, Engineering, High-Temp
    #  - 3D Printing Surface Guide (3DSourced/MatterHackers): generic Glass, Garolite (G10)
    #  - Anycubic + Prusa product pages: PEI Spring Steel and Satin variants
    now = datetime.now(UTC)
    op.bulk_insert(
        sa.table(
            "build_plate",
            sa.column("name", sa.String),
            sa.column("surface_type", sa.String),
            sa.column("finish", sa.String),
            sa.column("manufacturer", sa.String),
            sa.column("bed_temp_min", sa.Integer),
            sa.column("bed_temp_max", sa.Integer),
            sa.column("compatible_materials", sa.String),
            sa.column("notes", sa.String),
            sa.column("created_at", sa.DateTime),
            sa.column("updated_at", sa.DateTime),
        ),
        [
            {
                "name": "Bambu Cool Plate SuperTack",
                "surface_type": "Cool Plate",
                "finish": "smooth",
                "manufacturer": "Bambu Lab",
                "bed_temp_min": 35,
                "bed_temp_max": 45,
                "compatible_materials": "PLA",
                "notes": "Low-temp specialist. Strong PLA adhesion at 35–45 °C, reduces power and chamber heat.",
                "created_at": now, "updated_at": now,
            },
            {
                "name": "Bambu Smooth PEI Plate",
                "surface_type": "PEI",
                "finish": "smooth",
                "manufacturer": "Bambu Lab",
                "bed_temp_min": 55,
                "bed_temp_max": 80,
                "compatible_materials": "PLA, PETG, TPU",
                "notes": "Glossy bottom finish. Good all-rounder for low-to-mid temp filaments.",
                "created_at": now, "updated_at": now,
            },
            {
                "name": "Bambu Textured PEI Plate",
                "surface_type": "PEI",
                "finish": "textured",
                "manufacturer": "Bambu Lab",
                "bed_temp_min": 55,
                "bed_temp_max": 100,
                "compatible_materials": "PLA, PETG, ABS, ASA, PC, PA",
                "notes": "Best first-layer adhesion for functional parts. Powder-coat texture transfers to print bottom.",
                "created_at": now, "updated_at": now,
            },
            {
                "name": "Bambu Engineering Plate",
                "surface_type": "Engineering",
                "finish": "smooth",
                "manufacturer": "Bambu Lab",
                "bed_temp_min": 80,
                "bed_temp_max": 110,
                "compatible_materials": "ABS, ASA, PC, PA, PA-CF",
                "notes": "For engineering filaments. Use glue stick / 3DLAC to prevent over-bonding.",
                "created_at": now, "updated_at": now,
            },
            {
                "name": "Bambu High Temperature Plate",
                "surface_type": "High-Temperature",
                "finish": "textured",
                "manufacturer": "Bambu Lab",
                "bed_temp_min": 100,
                "bed_temp_max": 120,
                "compatible_materials": "ABS, PC, PA-CF, PEI, PEEK",
                "notes": "X1E / chamber-heated machines. Engineering / high-temp materials.",
                "created_at": now, "updated_at": now,
            },
            {
                "name": "Anycubic PEI Spring Steel (Smooth)",
                "surface_type": "PEI",
                "finish": "smooth",
                "manufacturer": "Anycubic",
                "bed_temp_min": 55,
                "bed_temp_max": 85,
                "compatible_materials": "PLA, PETG, TPU",
                "notes": "Magnetic spring-steel base, smooth PEI top. Standard with Kobra 2/3.",
                "created_at": now, "updated_at": now,
            },
            {
                "name": "Anycubic PEI Spring Steel (Textured)",
                "surface_type": "PEI",
                "finish": "textured",
                "manufacturer": "Anycubic",
                "bed_temp_min": 55,
                "bed_temp_max": 100,
                "compatible_materials": "PLA, PETG, ABS, ASA",
                "notes": "Textured PEI variant for stronger adhesion + matte bottom.",
                "created_at": now, "updated_at": now,
            },
            {
                "name": "Prusa Smooth PEI",
                "surface_type": "PEI",
                "finish": "smooth",
                "manufacturer": "Prusa",
                "bed_temp_min": 55,
                "bed_temp_max": 100,
                "compatible_materials": "PLA, PETG, ABS, ASA",
                "notes": "Original Prusa smooth sheet. Re-coat every 3–6 months.",
                "created_at": now, "updated_at": now,
            },
            {
                "name": "Prusa Textured PEI",
                "surface_type": "PEI",
                "finish": "textured",
                "manufacturer": "Prusa",
                "bed_temp_min": 55,
                "bed_temp_max": 110,
                "compatible_materials": "PLA, PETG, ABS, ASA, TPU",
                "notes": "Textured Prusa sheet. Hides first-layer artefacts, broad material range.",
                "created_at": now, "updated_at": now,
            },
            {
                "name": "Prusa Satin Powder-Coated",
                "surface_type": "PEI",
                "finish": "satin",
                "manufacturer": "Prusa",
                "bed_temp_min": 55,
                "bed_temp_max": 100,
                "compatible_materials": "PLA, PETG, ABS",
                "notes": "Powder-coated satin finish. Slightly grippier than smooth, less rough than textured.",
                "created_at": now, "updated_at": now,
            },
            {
                "name": "Generic Glass Bed",
                "surface_type": "Glass",
                "finish": "smooth",
                "manufacturer": None,
                "bed_temp_min": 50,
                "bed_temp_max": 110,
                "compatible_materials": "PLA, PETG, ABS",
                "notes": "Perfectly flat, lasts years. Needs adhesive (glue stick / hairspray / 3DLAC) for most filaments.",
                "created_at": now, "updated_at": now,
            },
            {
                "name": "Generic Garolite (G10/FR4)",
                "surface_type": "Garolite",
                "finish": "textured",
                "manufacturer": None,
                "bed_temp_min": 60,
                "bed_temp_max": 120,
                "compatible_materials": "Nylon, PA, PA-CF, ABS",
                "notes": "Fiberglass-reinforced. Best surface for nylon — withstands high temps without warping.",
                "created_at": now, "updated_at": now,
            },
            {
                "name": "Generic Carborundum / Glass",
                "surface_type": "Glass",
                "finish": "textured",
                "manufacturer": None,
                "bed_temp_min": 50,
                "bed_temp_max": 100,
                "compatible_materials": "PLA, PETG, ABS",
                "notes": "Crystal-textured glass (Creality and others). Microscopic grip without adhesive for PLA.",
                "created_at": now, "updated_at": now,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_profile', schema=None) as batch_op:
        batch_op.drop_constraint('fk_print_profile_build_plate', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_print_profile_build_plate_id'))
        batch_op.drop_column('build_plate_id')

    with op.batch_alter_table('build_plate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_plate_name'))

    op.drop_table('build_plate')
    # ### end Alembic commands ###
